### ISSUE TITLE
Installation of Boostime

### ISSUE THREAD

**Issue by Allisterh** [AlbertoAlmuinha/boostime#2]
How do I get to install Boostime since catboost is not available for R. Every time I try to install from R the build fails because catboost is not available..

**Comment by Steviey** [comment]
**catboost** is available for R, not via CRAN, but via there website. 
It also works with tidymodels via **treesnip** like lightGbm does. I just tested engine: **boost_arima() > auto_arima_catboost** successfully. boost_arima() > auto_arima_lightgbm failed.

**Comment by AlbertoAlmuinha** [comment]
There is an issue with lightgbm and that's the reason of the failure. I think the people of the package was working on that.
